
name: Build and publish hass-pyscript-jupyter Docker Images

on:
  #防止fork乱用action设置只能手动触发构建
  workflow_dispatch:

jobs:
  build-test-publish-images:
    name: Build, test, and publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Setup docker to build for multiple platforms, see:
      # https://github.com/docker/build-push-action/tree/master#usage
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # dependabot updates to latest release

      - name: Set up Docker Buildx (for multi-arch builds)
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0 # dependabot updates to latest release

      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main -f Makefile-hass-pyscript-jupyter dev-env

      - name: Build Docker Images
        run: make -C main -f Makefile-hass-pyscript-jupyter build-all-multi
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain


      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Images to DockerHub
        run: make -C main -f Makefile-hass-pyscript-jupyter push-all-multi
